CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipo_cliente ENUM('Pessoa Física', 'Pessoa Jurídica') NOT NULL,
  nome_completo VARCHAR(200) NOT NULL,
  data_nascimento DATE NULL,
  genero ENUM('Masculino', 'Feminino', 'Outro') NULL,
  estado_civil ENUM('Solteiro', 'Casado', 'Divorciado', 'Viúvo') NULL,
  documento_tipo ENUM('BI', 'Passaporte', 'NUIT', 'DIRE') NOT NULL,
  documento_numero VARCHAR(50) NOT NULL UNIQUE,
  documento_validade DATE NULL,
  nuit VARCHAR(20) NULL,
  telefone_principal VARCHAR(20) NOT NULL,
  telefone_alternativo VARCHAR(20) NULL,
  email VARCHAR(100) NULL,
  endereco_completo TEXT NOT NULL,
  zona_id INT NOT NULL,
  bairro VARCHAR(100) NULL,
  cidade VARCHAR(100) NOT NULL,
  provincia VARCHAR(100) NOT NULL,
  coordenadas_gps VARCHAR(50) NULL,
  limite_credito DECIMAL(15,2) NOT NULL,
  perfil_risco ENUM('A', 'B', 'C', 'D') NOT NULL,
  score INT NOT NULL,
  contacto_emergencia_nome VARCHAR(100) NULL,
  contacto_emergencia_telefone VARCHAR(20) NULL,
  contacto_emergencia_parentesco VARCHAR(100) NULL,
  observacoes TEXT NULL,
  cliente_ativo BOOLEAN NOT NULL DEFAULT TRUE,
  foto_perfil VARCHAR(255) NULL,
  documentos_anexos JSON NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  criado_por INT NOT NULL
);
