CREATE TABLE guarantees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo_garantia VARCHAR(50) NOT NULL UNIQUE,
  loan_id INT NOT NULL,
  client_id INT NOT NULL,
  tipo_garantia ENUM('Sem Garantia','Aval/Fiador','Bem Móvel','Bem Imóvel','Cheque Caução','Depósito Caução','Outro') NOT NULL,
  subtipo_garantia ENUM('Carro','Moto','Equipamento','Joias','Casa','Terreno') NULL,
  descricao TEXT NOT NULL,
  valor_estimado DECIMAL(15,2) NOT NULL DEFAULT 0,
  valor_avaliado DECIMAL(15,2) NULL,
  moeda VARCHAR(3) NOT NULL DEFAULT 'MZN',
  data_avaliacao DATE NULL,
  avaliador VARCHAR(100) NULL,
  estado_conservacao ENUM('Novo','Bom','Razoável','Mau') NULL,
  localizacao_garantia VARCHAR(255) NULL,
  documentos_anexos JSON NULL,
  fotos_garantia JSON NULL,
  status ENUM('Em Avaliação','Ativa','Libertada','Penhorada','Executada','Cancelada') NOT NULL DEFAULT 'Em Avaliação',
  aprovado_por INT NULL,
  data_aprovacao TIMESTAMP NULL,
  data_penhor DATE NULL,
  notificacao_meio VARCHAR(50) NULL,
  notificacao_data TIMESTAMP NULL,
  data_libertacao DATE NULL,
  data_execucao DATE NULL,
  motivo_execucao TEXT NULL,
  valor_recuperado DECIMAL(15,2) NULL,
  observacoes TEXT NULL,
  registado_por INT NOT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_guarantees_loan (loan_id),
  KEY idx_guarantees_status (status),
  CONSTRAINT fk_guarantees_loan FOREIGN KEY (loan_id) REFERENCES loans(id),
  CONSTRAINT fk_guarantees_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_guarantees_user FOREIGN KEY (registado_por) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE guarantors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  guarantee_id INT NOT NULL,
  nome_completo VARCHAR(200) NOT NULL,
  documento_tipo ENUM('BI','Passaporte','NUIT') NOT NULL,
  documento_numero VARCHAR(50) NOT NULL,
  telefone_principal VARCHAR(20) NOT NULL,
  telefone_alternativo VARCHAR(20) NULL,
  email VARCHAR(100) NULL,
  endereco_completo VARCHAR(255) NOT NULL,
  profissao VARCHAR(100) NULL,
  rendimento_mensal DECIMAL(15,2) NULL,
  relacao_com_cliente VARCHAR(100) NULL,
  documentos_anexos JSON NULL,
  status ENUM('Ativo','Inativo') NOT NULL DEFAULT 'Ativo',
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_guarantors_guarantee (guarantee_id),
  CONSTRAINT fk_guarantors_guarantee FOREIGN KEY (guarantee_id) REFERENCES guarantees(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE guarantee_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  guarantee_id INT NOT NULL,
  status_anterior VARCHAR(50) NOT NULL,
  status_novo VARCHAR(50) NOT NULL,
  motivo TEXT NULL,
  utilizador_id INT NULL,
  data_movimento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_guarantee_movements_guarantee (guarantee_id),
  CONSTRAINT fk_guarantee_movements_guarantee FOREIGN KEY (guarantee_id) REFERENCES guarantees(id) ON DELETE CASCADE,
  CONSTRAINT fk_guarantee_movements_user FOREIGN KEY (utilizador_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
