CREATE TABLE loans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero_contrato VARCHAR(50) NOT NULL UNIQUE,
  client_id INT NOT NULL,
  valor_emprestado DECIMAL(15,2) NOT NULL,
  moeda VARCHAR(10) NOT NULL DEFAULT 'MZN',
  taxa_juros DECIMAL(5,2) NOT NULL,
  tipo_juros ENUM('Simples','Composto') NOT NULL,
  sistema_amortizacao ENUM('Tabela Price','SAC','Americano','Bullet') NOT NULL,
  modalidade ENUM('Mensal','Semanal','Quinzenal','Diário') NOT NULL,
  num_parcelas INT NOT NULL,
  valor_parcela DECIMAL(15,2) NOT NULL,
  valor_total_juros DECIMAL(15,2) NOT NULL,
  valor_total_receber DECIMAL(15,2) NOT NULL,
  valor_pago DECIMAL(15,2) NOT NULL DEFAULT 0,
  saldo_devedor DECIMAL(15,2) NOT NULL,
  data_inicio DATE NOT NULL,
  data_vencimento DATE NOT NULL,
  dia_vencimento INT NULL,
  garantia_id INT NULL,
  carteira_id INT NOT NULL,
  status ENUM('Pendente','Ativo','Quitado','Vencido','Em Atraso','Cancelado','Rejeitado') NOT NULL DEFAULT 'Pendente',
  fase_atual ENUM('Análise','Aprovação','Desembolso','Em Curso','Concluído') NULL,
  aprovado_por INT NULL,
  data_aprovacao TIMESTAMP NULL,
  desembolsado_por INT NULL,
  data_desembolso TIMESTAMP NULL,
  observacoes TEXT NULL,
  documento_contrato VARCHAR(255) NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  criado_por INT NOT NULL,
  CONSTRAINT fk_loans_client FOREIGN KEY (client_id) REFERENCES clients(id),
  CONSTRAINT fk_loans_wallet FOREIGN KEY (carteira_id) REFERENCES wallets(id),
  CONSTRAINT fk_loans_guarantee FOREIGN KEY (garantia_id) REFERENCES guarantees(id),
  CONSTRAINT fk_loans_criado FOREIGN KEY (criado_por) REFERENCES users(id),
  CONSTRAINT fk_loans_aprovado FOREIGN KEY (aprovado_por) REFERENCES users(id),
  CONSTRAINT fk_loans_desembolsado FOREIGN KEY (desembolsado_por) REFERENCES users(id)
);

CREATE TABLE loan_installments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  loan_id INT NOT NULL,
  num_parcela INT NOT NULL,
  valor_parcela DECIMAL(15,2) NOT NULL,
  valor_juros DECIMAL(15,2) NOT NULL,
  valor_principal DECIMAL(15,2) NOT NULL,
  saldo_apos_pagamento DECIMAL(15,2) NOT NULL,
  data_vencimento DATE NOT NULL,
  data_pagamento DATE NULL,
  valor_pago DECIMAL(15,2) NULL,
  status ENUM('Pendente','Pago','Atrasado','Parcialmente Pago','Cancelado') NOT NULL DEFAULT 'Pendente',
  dias_atraso INT NULL,
  multa DECIMAL(15,2) NULL,
  observacoes TEXT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_loan_parcela (loan_id, num_parcela),
  CONSTRAINT fk_installments_loan FOREIGN KEY (loan_id) REFERENCES loans(id) ON DELETE CASCADE
);
