CREATE TABLE wallets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  codigo VARCHAR(20) NOT NULL UNIQUE,
  tipo ENUM('Caixa','Mpesa','E-Mola','Banco','Outro') NOT NULL,
  descricao TEXT NULL,
  numero_conta VARCHAR(50) NULL,
  iban VARCHAR(50) NULL,
  titular VARCHAR(200) NULL,
  agencia VARCHAR(100) NULL,
  saldo_inicial DECIMAL(15,2) NOT NULL DEFAULT 0,
  saldo_atual DECIMAL(15,2) NOT NULL DEFAULT 0,
  saldo_disponivel DECIMAL(15,2) NOT NULL DEFAULT 0,
  saldo_bloqueado DECIMAL(15,2) NULL DEFAULT 0,
  moeda VARCHAR(10) NOT NULL DEFAULT 'MZN',
  limite_minimo DECIMAL(15,2) NULL,
  limite_maximo DECIMAL(15,2) NULL,
  responsavel_id INT NULL,
  status ENUM('Ativa','Inativa','Bloqueada','Encerrada') NOT NULL DEFAULT 'Ativa',
  observacoes TEXT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  criado_por INT NOT NULL,
  KEY idx_wallets_status (status)
);

CREATE TABLE transactions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo_transacao VARCHAR(50) NOT NULL UNIQUE,
  wallet_id INT NOT NULL,
  tipo ENUM('Entrada','Saída','Transferência') NOT NULL,
  subtipo ENUM('Pagamento Empréstimo','Desembolso Empréstimo','Despesa','Transferência Interna','Depósito','Levantamento','Comissão','Multa','Estorno','Ajuste') NOT NULL,
  valor DECIMAL(15,2) NOT NULL,
  saldo_anterior DECIMAL(15,2) NOT NULL,
  saldo_posterior DECIMAL(15,2) NOT NULL,
  descricao TEXT NOT NULL,
  categoria VARCHAR(100) NULL,
  referencia VARCHAR(100) NULL,
  payment_id INT NULL,
  loan_id INT NULL,
  expense_id INT NULL,
  wallet_destino_id INT NULL,
  data_transacao TIMESTAMP NOT NULL,
  comprovativo VARCHAR(255) NULL,
  status ENUM('Confirmada','Pendente','Cancelada','Estornada') NOT NULL DEFAULT 'Confirmada',
  observacoes TEXT NULL,
  registado_por INT NOT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_trx_wallet (wallet_id),
  CONSTRAINT fk_trx_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id)
);

CREATE TABLE expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo_despesa VARCHAR(50) NOT NULL UNIQUE,
  wallet_id INT NOT NULL,
  categoria ENUM('Transporte','Material','Salário','Renda','Água','Energia','Internet','Manutenção','Marketing','Outro') NOT NULL,
  descricao TEXT NOT NULL,
  valor DECIMAL(15,2) NOT NULL,
  data_despesa DATE NOT NULL,
  fornecedor VARCHAR(200) NULL,
  numero_factura VARCHAR(50) NULL,
  comprovativo VARCHAR(255) NULL,
  status ENUM('Pendente','Aprovada','Paga','Rejeitada','Cancelada') NOT NULL DEFAULT 'Pendente',
  aprovado_por INT NULL,
  data_aprovacao TIMESTAMP NULL,
  observacoes TEXT NULL,
  registado_por INT NOT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_exp_wallet (wallet_id),
  CONSTRAINT fk_exp_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id)
);

CREATE TABLE transfers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo_transferencia VARCHAR(50) NOT NULL UNIQUE,
  wallet_origem_id INT NOT NULL,
  wallet_destino_id INT NOT NULL,
  valor DECIMAL(15,2) NOT NULL,
  taxa DECIMAL(15,2) NULL DEFAULT 0,
  valor_total DECIMAL(15,2) NOT NULL,
  descricao TEXT NOT NULL,
  data_transferencia TIMESTAMP NOT NULL,
  comprovativo VARCHAR(255) NULL,
  status ENUM('Pendente','Concluída','Cancelada','Falhou') NOT NULL DEFAULT 'Concluída',
  observacoes TEXT NULL,
  registado_por INT NOT NULL,
  data_registo TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_trf_origem FOREIGN KEY (wallet_origem_id) REFERENCES wallets(id),
  CONSTRAINT fk_trf_destino FOREIGN KEY (wallet_destino_id) REFERENCES wallets(id)
);

CREATE TABLE wallet_movements (
  id INT AUTO_INCREMENT PRIMARY KEY,
  wallet_id INT NOT NULL,
  transaction_id INT NULL,
  transfer_id INT NULL,
  expense_id INT NULL,
  tipo_movimento ENUM('Entrada','Saída','Transferência') NOT NULL,
  valor DECIMAL(15,2) NOT NULL,
  saldo_anterior DECIMAL(15,2) NOT NULL,
  saldo_posterior DECIMAL(15,2) NOT NULL,
  descricao TEXT NOT NULL,
  data_movimento TIMESTAMP NOT NULL,
  registado_por INT NOT NULL,
  KEY idx_mov_wallet (wallet_id),
  CONSTRAINT fk_mov_wallet FOREIGN KEY (wallet_id) REFERENCES wallets(id)
);
